<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-02-19T12:00:20 IST" name="Default suite" finished-at="2024-02-19T12:00:21 IST" duration-ms="1557">
    <groups>
    </groups>
    <test started-at="2024-02-19T12:00:20 IST" name="Default test" finished-at="2024-02-19T12:00:21 IST" duration-ms="1557">
      <class name="Test_scenario.TestMethods">
        <test-method is-config="true" signature="initDriver()[pri:0, instance:Test_scenario.TestMethods@38c6f217]" started-at="2024-02-19T11:59:32 IST" name="initDriver" finished-at="2024-02-19T12:00:19 IST" duration-ms="47373" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method is-config="true" signature="initdriver()[pri:0, instance:Test_scenario.TestMethods@38c6f217]" started-at="2024-02-19T12:00:19 IST" name="initdriver" finished-at="2024-02-19T12:00:20 IST" depends-on-methods="com.pageobject.BaseClass.initDriver" duration-ms="441" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initdriver -->
        <test-method signature="LoginToEgoc()[pri:0, instance:Test_scenario.TestMethods@38c6f217]" started-at="2024-02-19T12:00:20 IST" name="LoginToEgoc" finished-at="2024-02-19T12:00:20 IST" duration-ms="257" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginToEgoc -->
        <test-method signature="checkUserName()[pri:0, instance:Test_scenario.TestMethods@38c6f217]" started-at="2024-02-19T12:00:20 IST" name="checkUserName" finished-at="2024-02-19T12:00:21 IST" depends-on-methods="Test_scenario.TestMethods.LoginToEgoc" duration-ms="714" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkUserName -->
        <test-method signature="CheckFontSize()[pri:0, instance:Test_scenario.TestMethods@38c6f217]" started-at="2024-02-19T12:00:21 IST" name="CheckFontSize" finished-at="2024-02-19T12:00:21 IST" depends-on-methods="Test_scenario.TestMethods.checkUserName" duration-ms="22" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckFontSize -->
        <test-method signature="Logout()[pri:0, instance:Test_scenario.TestMethods@38c6f217]" started-at="2024-02-19T12:00:21 IST" name="Logout" finished-at="2024-02-19T12:00:21 IST" depends-on-methods="Test_scenario.TestMethods.CheckFontSize" duration-ms="44" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Logout -->
        <test-method signature="Loginerror()[pri:0, instance:Test_scenario.TestMethods@38c6f217]" started-at="2024-02-19T12:00:21 IST" name="Loginerror" finished-at="2024-02-19T12:00:21 IST" depends-on-methods="Test_scenario.TestMethods.Logout" duration-ms="372" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [404 - Unauthorised User] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [404 - Unauthorised User] but found []
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at base.LoginErrorCheck.ErrorMessage(LoginErrorCheck.java:48)
at Test_scenario.TestMethods.Loginerror(TestMethods.java:60)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Loginerror -->
        <test-method is-config="true" signature="aftertest()[pri:0, instance:Test_scenario.TestMethods@38c6f217]" started-at="2024-02-19T12:00:21 IST" name="aftertest" finished-at="2024-02-19T12:00:21 IST" duration-ms="102" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftertest -->
      </class> <!-- Test_scenario.TestMethods -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
